# Generated by Django 2.2.1 on 2019-05-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=500)),
                ('project_description', models.TextField()),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
