# Generated by Django 2.2.1 on 2019-06-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
